# Generated by Django 5.2.9 on 2026-01-15 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_wafflevariety_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=70)),
                ('chai_varieties', models.ManyToManyField(related_name='stores', to='waffle.wafflevariety')),
            ],
        ),
        migrations.CreateModel(
            name='WaffleCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('waffle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='waffle.wafflevariety')),
            ],
        ),
        migrations.CreateModel(
            name='WaffleReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='waffle.wafflevariety')),
            ],
        ),
    ]
