# Generated by Django 5.2.9 on 2026-01-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0003_store_wafflecertificate_wafflereviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_varieties',
            new_name='waffle_varieties',
        ),
    ]
